/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AfterCourse;

import java.io.DataInputStream;
import java.io.FileInputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class AfterCourse extends javax.swing.JFrame {

    /**
     * Creates new form AfterCourse
     */
    public AfterCourse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JButton();
        addstd = new javax.swing.JButton();
        addcrs = new javax.swing.JButton();
        Data = new javax.swing.JButton();
        data = new javax.swing.JButton();
        buy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        addstd.setText("Add Student");
        addstd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstdActionPerformed(evt);
            }
        });

        addcrs.setText("Add Course");
        addcrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcrsActionPerformed(evt);
            }
        });

        Data.setText("Students");
        Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataActionPerformed(evt);
            }
        });

        data.setText("Courses");
        data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataActionPerformed(evt);
            }
        });

        buy.setText("Paying");
        buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(data)
                        .addGap(10, 10, 10))
                    .addComponent(addstd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addcrs, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(layout.createSequentialGroup()
                .addComponent(exit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                .addComponent(buy))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 295, Short.MAX_VALUE)
                .addComponent(Data)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addcrs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(data)
                .addGap(18, 18, 18)
                .addComponent(addstd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Data)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(buy)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed

        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    courses crsclss;
    student stdclss;
    public static ArrayList<student> students=new ArrayList<>();
    public static ArrayList<courses> course=new ArrayList<>();
    addcourse adcrs;
    studentt std;
    coursefile crsf;
    int counter2=0;
    private void addcrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcrsActionPerformed

        if(adcrs==null)
                adcrs=new addcourse();
        adcrs.setVisible(true);
    }//GEN-LAST:event_addcrsActionPerformed

    private void addstdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstdActionPerformed

        String name=JOptionPane.showInputDialog(this, "Enter Name:");
        int ID=Integer.parseInt(JOptionPane.showInputDialog(this, "Enter ID:"));
        String lvl=JOptionPane.showInputDialog(this, "Enter Level:");
        
        students.add(stdclss=new student(name,ID,lvl));
        if(std==null)
        std=new studentt();
            std.start();
    }//GEN-LAST:event_addstdActionPerformed

    private void dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataActionPerformed

        String total="";
        for(int i=0;i<course.size();i++)
        {
            total=total+course.get(i).Getdata()+"\n";
        }
        JOptionPane.showMessageDialog(this, total);
    }//GEN-LAST:event_dataActionPerformed

    private void DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataActionPerformed

        String total="";
        for(int i=0;i<students.size();i++)
        {
            total=total+students.get(i).GetDatas()+"\n";
        }
        JOptionPane.showMessageDialog(this, total);
    }//GEN-LAST:event_DataActionPerformed

    buying bys;
    private void buyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyActionPerformed

        if(bys==null)
            bys=new buying();
        bys.setVisible(true);
    }//GEN-LAST:event_buyActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        if(counter2==0)
        {
        String str="";
        String str2="";
        int id = 0;
        String level = null;
        boolean paid;
        
        int count=0;
        try {
            FileInputStream f1=new FileInputStream("/Users/dodo/Desktop/Students.txt");
            DataInputStream d1=new DataInputStream(f1);
            while(f1.available()>0)
            {

                str=d1.readUTF().trim();
            if (count==0)
            {
                str2=str;
                count++;
            }
            else if(count==1)
            {
                id=Integer.parseInt(str);
                count++;
            }else if(count==2)
            {
                level=str;
                count++;
            }else if(count==3)
            {
                if(str.equals(false))
                    paid=false;
                else
                    paid =true;
                count++;
            
               students.add(stdclss=new student(str2,id,level,paid));
               count=0;
            }
            }
            
            d1.close();
            f1.close();
            
            str="";
            str2="";
            id = 0;
            int price=0;
            int hrs=0;
            
            FileInputStream f2=new FileInputStream("/Users/dodo/Desktop/Courses.txt");
            DataInputStream d2=new DataInputStream(f2);
            while(f2.available()>0)
            {

                str=d2.readUTF().trim();
            if (count==0)
            {
                str2=str;
                count++;
            }
            else if(count==1)
            {
                id=Integer.parseInt(str);
                count++;
            }else if(count==2)
            {
                price=Integer.parseInt(str);
                count++;
            }else if(count==3)
            {
                hrs=Integer.parseInt(str);
                count++;
            
               course.add(stdclss=new student(str2,id,price,hrs));
               if(f2.available()!=0)
               count=0;
               
            }
            }
            
            d1.close();
            f1.close();
            counter2++;
        } catch (Exception e) {
       
        }
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AfterCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AfterCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AfterCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AfterCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AfterCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Data;
    private javax.swing.JButton addcrs;
    private javax.swing.JButton addstd;
    private javax.swing.JButton buy;
    private javax.swing.JButton data;
    private javax.swing.JButton exit;
    // End of variables declaration//GEN-END:variables
}
