/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Henawy;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author dodo
 */
public class Assignment1 extends javax.swing.JFrame {

    /**
     * Creates new form Assignment1
     */
    public Assignment1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JButton();
        enter = new javax.swing.JButton();
        show = new javax.swing.JButton();
        sum = new javax.swing.JButton();
        avg = new javax.swing.JButton();
        random = new javax.swing.JButton();
        Random = new javax.swing.JButton();
        Sodoko = new javax.swing.JButton();
        counter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        enter.setText("Enter data");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });

        show.setText("Show Data");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        sum.setText("Sum of Rows");
        sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumActionPerformed(evt);
            }
        });

        avg.setText("Avg of column");
        avg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avgActionPerformed(evt);
            }
        });

        random.setText("rnd array ");
        random.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomActionPerformed(evt);
            }
        });

        Random.setText("Random");
        Random.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandomActionPerformed(evt);
            }
        });

        Sodoko.setText("Sodoko");
        Sodoko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SodokoActionPerformed(evt);
            }
        });

        counter.setText("Count");
        counter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                counterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(show)
                    .addComponent(enter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(random, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Random)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avg)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sodoko, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(counter, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enter)
                    .addComponent(random))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(show)
                    .addComponent(Random))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avg)
                    .addComponent(Sodoko))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(counter)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed

        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    int[][] x=new int[5][3];
    String total="";
    
    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed

                
        for(int i=0;i<5;i++)
        {
            for(int o=0;o<3;o++)
            {
                String s=JOptionPane.showInputDialog(this , "Enter Data for Row "+i+" Column "+o);
                x [i][o] =Integer.parseInt(s);
                total = total+x[i][o]+"    ";
            }
            total=total+"\n";
        }
        
    }//GEN-LAST:event_enterActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed

        JOptionPane.showMessageDialog(this, total);
    }//GEN-LAST:event_showActionPerformed

    private void sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumActionPerformed

        int sum=0;
        String total2="";
        for(int i=0;i<5;i++)
        {
            for(int o=0;o<3;o++)
            {
                sum = sum+x[i][o];
            }
            total2=total2+sum+"\n";
            
            sum=0;
        }
        JOptionPane.showMessageDialog(this, total2);
    }//GEN-LAST:event_sumActionPerformed

    private void avgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avgActionPerformed

        int avg=0;
        int count=0;
        String total3="";
        for(int i=0;i<3;i++)
        {
            for(int o=0;o<5;o++)
            {
                avg =avg+ x[o][i];
                count++;
            }
            avg = avg/count ;
            total3=total3+avg+"    ";
            avg=0;
        }
        JOptionPane.showMessageDialog(this, total3);
    }//GEN-LAST:event_avgActionPerformed

    private void randomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomActionPerformed

        int [][] z=new int[5][3];
        Random r=new Random();
        String total4="";
        int count;
        //int count2 =0;
        
        for(int i=0;i<5;i++) //rows
        {
            
            for(int o=0;o<3;o++) //column
            {int c=r.nextInt(30);
              
                
              do{
                  count=0;
                   for(int k=0;k<5;k++)
                    {
                        if(c==z[k][o])
                        {
                           c=r.nextInt(30);
                           count++;
                           
                        }
                    }
                }while(count!=0);
                
               z[i][o]=c;
               total4=total4+z[i][o]+"    ";
            }
                
            total4=total4+"\n";
        }
        JOptionPane.showMessageDialog(this, total4);
    }//GEN-LAST:event_randomActionPerformed

    private void RandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RandomActionPerformed

        int [][] z=new int[5][3];
        Random r=new Random();
        String total4="";
        int c=r.nextInt(30);
        
        for(int i=0;i<5;i++) //rows
        {
            
            for(int o=0;o<3;o++) //column
            {
              for(int q=0;q<3;q++)
              {
                for(int k=0;k<5;k++)
                {
                    for(int l=0;l<3;l++)
                    {
                         if(c==z[k][l])
                         c=r.nextInt(30);
                    }
                }
              }    
               z[i][o]=c;
               total4=total4+z[i][o]+"    ";
            }
                
            total4=total4+"\n";
        }
        JOptionPane.showMessageDialog(this, total4);
    }//GEN-LAST:event_RandomActionPerformed

    private void SodokoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SodokoActionPerformed

        int [][] z=new int[9][9];
        Random r=new Random();
        String total4="";
        int count = 0;
        int c=r.nextInt(10);
        
        for(int i=0;i<9;i++) //rows
        {
            
            for(int o=0;o<9;o++) //column
            {
             c=r.nextInt(10);
                 for(int q=0;q<9;q++)
                {
                     for(int k=0;k<9;k++)
                    {
                         for(int l=0;l<9;l++)
                        {
                            if(l!=z[l][o])
                             count++;
                                 for(int a=0;a<9;a++)
                                {
                                   if(c==z[a][o])
                                   c=r.nextInt(10);
                                }
                        }
                     if(count==8)
                     c=r.nextInt(10);
                    }
                }    
             z[i][o]=c;
             total4=total4+z[i][o]+"    ";
            }
                
         total4=total4+"\n";
        }
     JOptionPane.showMessageDialog(this, total4);
    }//GEN-LAST:event_SodokoActionPerformed

    private void counterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_counterActionPerformed

        int [][] z=new int[9][9];
        Random r=new Random();
        String total4="";
        String total2="";
        int [] q=new int[10];
        int c=r.nextInt(10);
        
        for(int i=0;i<9;i++) //rows
        {
            
            for(int o=0;o<9;o++) //column
            {
             c=r.nextInt(10);
             
             z[i][o]=c;
             
             total4=total4+z[i][o]+"    ";
             
            }
            
          total4=total4+"\n";
        }
        
        for(int i=0;i<9;i++)
        {
            for(int o=0;o<9;o++)
            {
                for(int u=0;u<10;u++)
                {
                    if(z[i][o]==u)
                    {
                      q [u]++;
                    }
                }
             
            }
            total2=total2+"Row"+i+" ";
            for(int y=0;y<10;y++)
            {
                
             total2=total2+q [y]+" x"+y+"  ";
              q [y]=0;
                
            }
            total2=total2+"\n";
        }
        
     JOptionPane.showMessageDialog(this, total4);
     JOptionPane.showMessageDialog(this, total2, "Counter", 0);
     
     
    }//GEN-LAST:event_counterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Assignment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Assignment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Assignment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Assignment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Assignment1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Random;
    private javax.swing.JButton Sodoko;
    private javax.swing.JButton avg;
    private javax.swing.JButton counter;
    private javax.swing.JButton enter;
    private javax.swing.JButton exit;
    private javax.swing.JButton random;
    private javax.swing.JButton show;
    private javax.swing.JButton sum;
    // End of variables declaration//GEN-END:variables
}
