/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Henawy;


import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;

public class Runtime extends javax.swing.JFrame {

    /**
     * Creates new form Runtime
     */
    public Runtime() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Devision = new javax.swing.JButton();
        folder = new javax.swing.JButton();
        read = new javax.swing.JButton();
        search = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Devision.setText("Devision");
        Devision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevisionActionPerformed(evt);
            }
        });

        folder.setText("Folder");
        folder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                folderActionPerformed(evt);
            }
        });

        read.setText("Read");
        read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readActionPerformed(evt);
            }
        });

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(exit)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(read))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(folder, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(search, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Devision, javax.swing.GroupLayout.Alignment.TRAILING)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(folder)
                .addGap(31, 31, 31)
                .addComponent(Devision)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(search)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(read)
                    .addComponent(exit)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DevisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevisionActionPerformed

        try{
        double x=Integer.parseInt(JOptionPane.showInputDialog(this, "Enter First no"));
        double y=Integer.parseInt(JOptionPane.showInputDialog(this, "Enter Second no"));
        double z=x/y;
        JOptionPane.showMessageDialog(this, z);
        }
        catch(ArithmeticException e)
        {
            JOptionPane.showMessageDialog(this, "No. Can't be divided by zero");
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Please Enter No.");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Sorry Try Again!");
        }
    }//GEN-LAST:event_DevisionActionPerformed

    private void folderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_folderActionPerformed

        try
        {
            FileOutputStream file1=new FileOutputStream("/Users/dodo/Desktop/Product.txt",true);
            DataOutputStream data=new DataOutputStream(file1);
            String name=JOptionPane.showInputDialog(this, "Enter name");
            String id=JOptionPane.showInputDialog(this, "Enter ID");
            String price=JOptionPane.showInputDialog(this, "Enter Price");
            String q=JOptionPane.showInputDialog(this, "Enter Quantity");
            data.writeUTF(name+"\n"+id+"\n"+price+"\n"+q+"\n\n");
            data.close();
            file1.close();
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_folderActionPerformed

    private void readActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readActionPerformed

        String str="";
        try {
            FileInputStream file1=new FileInputStream("/Users/dodo/Desktop/Product.txt");
            DataInputStream data=new DataInputStream(file1);
            while(data.available()>0)
            {
               str=str+data.readUTF();
            }
            JOptionPane.showMessageDialog(this, str);
            file1.close();
            data.close();
            
        } catch (Exception e) 
        {
           
        }
    }//GEN-LAST:event_readActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed

        String str="";
        String str2="";
        int count = 0;
        try {
            FileInputStream file1=new FileInputStream("/Users/dodo/Desktop/Product.txt");
            DataInputStream data=new DataInputStream(file1);
            String targetid=JOptionPane.showInputDialog(this, "Enter ID");
            while(data.available()>0)
            {
               str2=data.readUTF();
               str=str+str2;
               if(targetid.equals(str2.trim()))
                count++;
            }
            if(count==1)
            JOptionPane.showMessageDialog(this, str);
            file1.close();
            data.close();
            
        } catch (Exception e) 
        {
           
        }
    }//GEN-LAST:event_searchActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed

        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Runtime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Runtime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Runtime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Runtime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Runtime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Devision;
    private javax.swing.JButton exit;
    private javax.swing.JButton folder;
    private javax.swing.JButton read;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
