/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Henawy;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;

public class XOgame extends javax.swing.JFrame {

    /**
     * Creates new form XOgame
     */
    public XOgame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        XO = new javax.swing.ButtonGroup();
        exit = new javax.swing.JButton();
        startx = new javax.swing.JRadioButton();
        starto = new javax.swing.JRadioButton();
        reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        XO.add(startx);
        startx.setText("Start With X");
        startx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startxActionPerformed(evt);
            }
        });

        XO.add(starto);
        starto.setText("Start With O");
        starto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startoActionPerformed(evt);
            }
        });

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(exit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(startx)
                .addGap(61, 61, 61)
                .addComponent(starto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reset)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 271, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(startx)
                    .addComponent(starto)
                    .addComponent(reset)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed

        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    int counter=2;
    ArrayList<JButton> btns=new ArrayList<>();
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        int x=0;
        int y=0;
        
        for(int o=0;o<3;o++)
        {
            for(int i=0;i<3;i++)
            {
            JButton btn=new JButton();
        
            btn.setText("");
            btn.setBackground(Color.white);
            btn.setBounds(x, y, 70, 50);
            this.getContentPane().add(btn);
            btn.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    e.getSource();
                    
                    if(counter==0)
                    {
                        btn.setText("O");
                        counter=1;
                    }else
                    if(counter==1)
                    {
                        btn.setText("X");
                        counter=0;
                    }
                    
                    
                        if(btns.get(1).getText().equals(btns.get(4).getText())&&btns.get(4).getText().equals(btns.get(7).getText())&&
                                !btns.get(1).getText().equals("")&&!btns.get(4).getText().equals("")&&!btns.get(7).getText().equals(""))
                        {
                            btns.get(1).setBackground(Color.green);
                            btns.get(4).setBackground(Color.green);
                            btns.get(7).setBackground(Color.green);
                        }
                        
                        if(btns.get(0).getText().equals(btns.get(3).getText())&&btns.get(3).getText().equals(btns.get(6).getText())&&
                                !btns.get(0).getText().equals("")&&!btns.get(3).getText().equals("")&&!btns.get(6).getText().equals(""))
                        {
                            btns.get(0).setBackground(Color.green);
                            btns.get(3).setBackground(Color.green);
                            btns.get(6).setBackground(Color.green);
                        }
                        
                        if(btns.get(2).getText().equals(btns.get(5).getText())&&btns.get(5).getText().equals(btns.get(8).getText())&&
                                !btns.get(2).getText().equals("")&&!btns.get(5).getText().equals("")&&!btns.get(8).getText().equals(""))
                        {
                            btns.get(2).setBackground(Color.green);
                            btns.get(5).setBackground(Color.green);
                            btns.get(8).setBackground(Color.green);
                        }
                        
                        if(btns.get(0).getText().equals(btns.get(1).getText())&&btns.get(1).getText().equals(btns.get(2).getText())&&
                                !btns.get(0).getText().equals("")&&!btns.get(1).getText().equals("")&&!btns.get(2).getText().equals(""))
                        {
                            btns.get(0).setBackground(Color.green);
                            btns.get(1).setBackground(Color.green);
                            btns.get(2).setBackground(Color.green);
                        }
                        
                        if(btns.get(3).getText().equals(btns.get(4).getText())&&btns.get(4).getText().equals(btns.get(5).getText())&&
                                !btns.get(3).getText().equals("")&&!btns.get(4).getText().equals("")&&!btns.get(5).getText().equals(""))
                        {
                            btns.get(3).setBackground(Color.green);
                            btns.get(4).setBackground(Color.green);
                            btns.get(5).setBackground(Color.green);
                        }
                        
                        if(btns.get(6).getText().equals(btns.get(7).getText())&&btns.get(7).getText().equals(btns.get(8).getText())&&
                                !btns.get(6).getText().equals("")&&!btns.get(7).getText().equals("")&&!btns.get(8).getText().equals(""))
                        {
                            btns.get(6).setBackground(Color.green);
                            btns.get(7).setBackground(Color.green);
                            btns.get(8).setBackground(Color.green);
                        }
                        
                        if(btns.get(0).getText().equals(btns.get(4).getText())&&btns.get(4).getText().equals(btns.get(8).getText())&&
                                !btns.get(0).getText().equals("")&&!btns.get(4).getText().equals("")&&!btns.get(8).getText().equals(""))
                        {
                            btns.get(0).setBackground(Color.green);
                            btns.get(4).setBackground(Color.green);
                            btns.get(8).setBackground(Color.green);
                        }
                        
                        if(btns.get(2).getText().equals(btns.get(4).getText())&&btns.get(4).getText().equals(btns.get(6).getText())&&
                                !btns.get(2).getText().equals("")&&!btns.get(4).getText().equals("")&&!btns.get(6).getText().equals(""))
                        {
                            btns.get(2).setBackground(Color.green);
                            btns.get(4).setBackground(Color.green);
                            btns.get(6).setBackground(Color.green);
                        }
                        btn.setEnabled(false);
                }
            });
            btns.add(btn);
            x=x+70;
        }
            y=y+50;
            x=0;
        }
        this.repaint();
    }//GEN-LAST:event_formWindowOpened

    private void startxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startxActionPerformed

        starto.setEnabled(false);
        counter=1;
    }//GEN-LAST:event_startxActionPerformed

    private void startoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startoActionPerformed

        startx.setEnabled(false);
        counter=0;
    }//GEN-LAST:event_startoActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed

        counter=0;
        startx.setEnabled(true);
        starto.setEnabled(true);
        for(int i=0;i<btns.size();i++)
        {
            btns.get(i).setText("");
            btns.get(i).setBackground(Color.white);
            btns.get(i).setEnabled(true);
        }
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XOgame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XOgame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XOgame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XOgame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XOgame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup XO;
    private javax.swing.JButton exit;
    private javax.swing.JButton reset;
    private javax.swing.JRadioButton starto;
    private javax.swing.JRadioButton startx;
    // End of variables declaration//GEN-END:variables
}
